<?php
//########################################################################################
//##############################                            ##############################
//############################## THIS IS AUTOGENERATED FILE ##############################
//##############################                            ##############################
//########################################################################################
{$namespace}

%usages%

/**
 * Schema location {$schemaLocation}
{foreach from = $docDescriptionLines item = line}
{$line}
{/foreach}
{*foreach from = $trace item = tr}
 * {$tr}
{/foreach*}
 *
{foreach from = $docProperties item = doc}
{if $doc.type == 'property'}
 * @property {$doc.docType} ${$doc.name} {$doc.desc}
{/if}
{/foreach}
{foreach from = $docProperties item = doc}
{if $doc.type == 'method'}
 * @method {$doc.docType} {$doc.name}({$doc.argType}{$doc.argName}) {$doc.desc}
{/if}
{/foreach}
 */
class {$className}{$extends}
{
    {foreach from = $variableLines item = line}__REMOVE_LINE__
{$line}
    {/foreach}__REMOVE_LINE__

	public function __construct({$constructorArguments})
	{
        {foreach from = $constructorLines item = line}
{$line}
        {/foreach}__REMOVE_LINE__
    }

{foreach from = $methods item = met}
    /**
     * {$met.desc}
     * {$met.docArgument}
     * @throws \Exception
     * @return {$met.returnType}
     */
    public function {$met.name}({$met.argument}): {$met.returnType}
    {
{foreach from = $met.bodyLines item = bl}
        {$bl}
{/foreach}__REMOVE_LINE__
    }

{/foreach}__REMOVE_LINE__
}